from enum import Enum

class Columns(Enum):
    id = "id"
    imdb_id = "imdb_id"
    popularity = "popularity"
    budget = "budget"
    revenue = "revenue"
    original_title = "original_title"
    cast = "cast"
    homepage = "homepage"
    director = "director"
    tagline = "tagline"
    keywords = "keywords"
    overview = "overview"
    runtime = "runtime"
    genres = "genres"
    production_companies = "production_companies"
    release_date = "release_date"
    vote_count = "vote_count"
    vote_average = "vote_average"
    release_year = "release_year"
    budget_adj = "budget_adj"
    revenue_adj = "revenue_adj"
